"""
MANOE Agent Prompts Module
System prompts derived from the Storyteller framework.
"""

from .architect import ARCHITECT_SYSTEM_PROMPT, ARCHITECT_USER_PROMPT_TEMPLATE
from .critic import CRITIC_SYSTEM_PROMPT, CRITIC_USER_PROMPT_TEMPLATE
from .profiler import PROFILER_SYSTEM_PROMPT, PROFILER_USER_PROMPT_TEMPLATE
from .strategist import STRATEGIST_SYSTEM_PROMPT, STRATEGIST_USER_PROMPT_TEMPLATE
from .worldbuilder import WORLDBUILDER_SYSTEM_PROMPT, WORLDBUILDER_USER_PROMPT_TEMPLATE
from .writer import WRITER_SYSTEM_PROMPT, WRITER_USER_PROMPT_TEMPLATE

__all__ = [
    "ARCHITECT_SYSTEM_PROMPT",
    "ARCHITECT_USER_PROMPT_TEMPLATE",
    "PROFILER_SYSTEM_PROMPT",
    "PROFILER_USER_PROMPT_TEMPLATE",
    "STRATEGIST_SYSTEM_PROMPT",
    "STRATEGIST_USER_PROMPT_TEMPLATE",
    "WORLDBUILDER_SYSTEM_PROMPT",
    "WORLDBUILDER_USER_PROMPT_TEMPLATE",
    "WRITER_SYSTEM_PROMPT",
    "WRITER_USER_PROMPT_TEMPLATE",
    "CRITIC_SYSTEM_PROMPT",
    "CRITIC_USER_PROMPT_TEMPLATE",
]
