"""
MANOE Agent Prompts Module
System prompts derived from the Storyteller framework.
"""

from .advanced import (
    COMPLEXITY_CHECKLIST_PROMPT,
    CONTRADICTION_MAPS_PROMPT,
    EMOTIONAL_BEAT_SHEET_PROMPT,
    NARRATIVE_POSSIBILITIES_PROMPT,
    SENSORY_BLUEPRINT_PROMPT,
    SUBTEXT_DESIGN_PROMPT,
)
from .architect import ARCHITECT_SYSTEM_PROMPT, ARCHITECT_USER_PROMPT_TEMPLATE
from .critic import CRITIC_SYSTEM_PROMPT, CRITIC_USER_PROMPT_TEMPLATE
from .impact import IMPACT_ASSESSMENT_SYSTEM_PROMPT, IMPACT_ASSESSMENT_USER_PROMPT_TEMPLATE
from .originality import ORIGINALITY_CHECK_SYSTEM_PROMPT, ORIGINALITY_CHECK_USER_PROMPT_TEMPLATE
from .polish import POLISH_SYSTEM_PROMPT, POLISH_USER_PROMPT_TEMPLATE
from .profiler import PROFILER_SYSTEM_PROMPT, PROFILER_USER_PROMPT_TEMPLATE
from .strategist import STRATEGIST_SYSTEM_PROMPT, STRATEGIST_USER_PROMPT_TEMPLATE
from .worldbuilder import WORLDBUILDER_SYSTEM_PROMPT, WORLDBUILDER_USER_PROMPT_TEMPLATE
from .writer import WRITER_SYSTEM_PROMPT, WRITER_USER_PROMPT_TEMPLATE

__all__ = [
    "ARCHITECT_SYSTEM_PROMPT",
    "ARCHITECT_USER_PROMPT_TEMPLATE",
    "PROFILER_SYSTEM_PROMPT",
    "PROFILER_USER_PROMPT_TEMPLATE",
    "STRATEGIST_SYSTEM_PROMPT",
    "STRATEGIST_USER_PROMPT_TEMPLATE",
    "WORLDBUILDER_SYSTEM_PROMPT",
    "WORLDBUILDER_USER_PROMPT_TEMPLATE",
    "WRITER_SYSTEM_PROMPT",
    "WRITER_USER_PROMPT_TEMPLATE",
    "CRITIC_SYSTEM_PROMPT",
    "CRITIC_USER_PROMPT_TEMPLATE",
    "POLISH_SYSTEM_PROMPT",
    "POLISH_USER_PROMPT_TEMPLATE",
    "ORIGINALITY_CHECK_SYSTEM_PROMPT",
    "ORIGINALITY_CHECK_USER_PROMPT_TEMPLATE",
    "IMPACT_ASSESSMENT_SYSTEM_PROMPT",
    "IMPACT_ASSESSMENT_USER_PROMPT_TEMPLATE",
    # Advanced Features (Priority 3)
    "NARRATIVE_POSSIBILITIES_PROMPT",
    "CONTRADICTION_MAPS_PROMPT",
    "EMOTIONAL_BEAT_SHEET_PROMPT",
    "SENSORY_BLUEPRINT_PROMPT",
    "SUBTEXT_DESIGN_PROMPT",
    "COMPLEXITY_CHECKLIST_PROMPT",
]
